apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grade-submission-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Pavan0604/argocd-kubernetes
    targetRevision: HEAD 
    path: kustomize/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: grade-demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true